yaml-file: "./config.yaml"
tls-root-level: "tls"
db-root-level: "databases"
etcd-tls-enabled: true
etcd-ca-cert: "./tls/ca/ca-cert.pem"
etcd-cert: "./tls/webserver/client/client-cert.pem"
etcd-key: "./tls/webserver/client/client-key.pem"
etcd-hosts: "https://constantinopel.go-webserver.server:2379"
etcd-prefix: "configurations/reader-app"
output: true
output-file-path: "./etcd-configs-root.yaml"
update: true
update-keys: databases.mariadb,tls.mariadb,tls.redis
